version: '3.7'

services:
  mariadb:
    image: mariadb:10.3.11
    container_name: &db_container keycloak_mariadb
    restart: always
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
      - ./docker/mariadb/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: &db_name ${MYSQL_DATABASE}
      MYSQL_USER: &db_user ${MYSQL_USER}
      MYSQL_PASSWORD: &db_password ${MYSQL_PASSWORD}
    networks: 
      - mrivera

  keycloak:
    image: jboss/keycloak:4.6.0.Final
    container_name: &keycloak_container keycloak_server
    volumes:
      - ./docker:/usr/docker
    environment:
      KEYCLOAK_IMPORT: /usr/docker/keycloak/realm-export.json
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: mariadb
      DB_ADDR: *db_container
      DB_PORT: 3306
      DB_DATABASE: *db_name
      DB_USER: *db_user
      DB_PASSWORD: *db_password
    ports:
      - "8080:8080"
    entrypoint: bash /usr/docker/shell/keycloak.sh
    networks: 
      - mrivera

  php-fpm:
    build: ./docker/php
    image: mrivera/php-fpm:7.1
    container_name: mrivera-phpfpm
    volumes:
      - .:/www
    environment:
      KEYCLOAK_HOST: localhost
      KEYCLOAK_PORT: 8080
    networks: 
      - mrivera
    user: ${CURRENT_UID}
    command: bash /www/docker/shell/php-fpm.sh
    
  nginx:
    image: nginx:1.15
    container_name: mrivera-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      KEYCLOAK_HOST: *keycloak_container
      KEYCLOAK_PORT: 8080
    networks: 
      - mrivera
    command: bash /www/docker/shell/nginx.sh
      
networks:
  mrivera:
    name: mrivera/dev
