version: '3.7'

services:
  mariadb:
    image: mariadb:10.3.11
    restart: always
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
      - ./docker/mariadb/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: &db_name ${MYSQL_DATABASE}
      MYSQL_USER: &db_user ${MYSQL_USER}
      MYSQL_PASSWORD: &db_password ${MYSQL_PASSWORD}
    networks: 
      - default

  keycloak:
    image: jboss/keycloak:8.0.1
    volumes:
      - ./docker:/usr/docker
    environment:
      KEYCLOAK_IMPORT: /usr/docker/keycloak/realm-export.json
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: mariadb
      DB_ADDR: mariadb
      DB_PORT: 3306
      DB_DATABASE: *db_name
      DB_USER: *db_user
      DB_PASSWORD: *db_password
    ports:
      - "${KEYCLOAK_PORT}:8080"
    entrypoint: bash /usr/docker/shell/keycloak.sh
    networks: 
      - default

  webserver:
    image: mariort/php-nginx:3.0
    volumes:
      - .:/www
    ports:
      - "8000:80"
    environment: 
      - XDEBUG_CONFIG
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PUBLIC_HOST=${KEYCLOAK_PUBLIC_HOST}
      - KEYCLOAK_PORT=${KEYCLOAK_PORT}
    # env_file:
    #   - .env
    command: sh /www/docker/shell/webserver.sh
    networks: 
      - default
        
networks:
  default:
    name: mrivera/dev
